### PR TITLE
Benchmark and dependency updates

### PR DESCRIPTION
**Pull request by blt**
These two commits update quickcheck to 1.0 and adjust the benchmark strategy to cover more line variants, as well as measuring by cycles per byte rather than wall time. The first change is motivated by a desire to have Quickcheck's 1.0+'s state space exploration in place -- which did turn up issues in the `Arbitrary` implementations but not the actual parser -- and the second to measure the cycle cost of parsing lines. This PR introduces someone distinct changes together and if you'd like me to break it into two PRs I'll be happy to do that. 

The benchmark work demonstrates that parsing a line, today, has a constant overhead associated with it: the shorter the line the more this cost dominates, per byte. Short-line tests show a 10 cycle cost, long-line tests show 1 cycle, roughly. If lines are 2Kb a pop this'll mean we can parse lines at 2Gb/s. If we need to improve this constant overhead we will need to explore what this overhead actually is. My assumption today is that it's allocation costs -- the parser heap allocates a `Message` and its interior `Vec`s -- and we should be able to explore that by passing a `&mut Message` through a new `parse_message` variant.

### CODE REVIEW

**Comment by blt** [comment]
@FungusHumungus @jszwedko turns out I can't request review here since I'm not a collaborator. Would appreciate your thoughts.

**Comment by FungusHumungus** [comment]
Nice! Thanks for doing this.

>  and we should be able to explore that by passing a `&mut Message` through a new `parse_message` variant.

How would thish help with performance? Are you suggesting Vector reuses a single Message instance for multiple syslog messages?

**Comment by blt** [comment]
> Nice! Thanks for doing this.

Welcome! 

> How would thish help with performance? Are you suggesting Vector reuses a single Message instance for multiple syslog messages?

It might not help. :) All this'd accomplish would be to remove any constant overhead costs associated with allocating a `Message`, which would make the signal we get from benchmarks potentially more clear. I generated a [flamegraph](https://gist.github.com/blt/e3570370504a959035a1d9fe1d8f98bf) for the new example bin and noted that `structured_data` features prominently. That sub-parser allocs some little `Vec` instances, which is where the hunch comes from. An alternate approach to remove any overhead associated with allocation would be to wire in a bump allocator as `GlobalAlloc`, drive down that cost as low as possible. 

As to what the caller could do if we allowed them to pass a `&mut Message`, there's some neat things that would unlock. The caller could, of course, just heap allocate a `Message` and pass it through to be populated, so same basic outcome as here. If the caller were passing `Message` instances allocated from a slab there's the possibility to reuse, but how well that performs is going to depend entirely on the slab. A single `Message` instance in memory would bottleneck on your ability to clear it for reuse, so you'd want a handful around since we don't need to be penny pinch bytes. 

I would also be willing to believe that if we exposed an API surface to populate a `&mut Message` -- or otherwise isolated allocation costs -- it wouldn't be _that_ much faster. Totally possible. Another interesting avenue for exploration would be to see if we can't expose something to parse multiple lines at once. We already have a hint from this PR that the larger the line the cheaper the per-byte cost. Does the same hold true if we're parsing multiple lines in one pass? I'm not a nom expert by any means so if you know of any low-hanging fruit we could look into I'd be curious to know it. 

Honestly, absent any reason to optimize further the performance of the library as-is strikes me as good. For any vector topology with a syslog source at the root we can't get any faster than our ability to parse, so this here sets a baseline.

**Comment by FungusHumungus** [comment]
I suppose if nothing else, it is reassuring to my ego that you haven't found any major obvious flaws! But it is worth pushing it as far as is practical.

I've created #8 to continue discussing the performance issues.

**Pull request merged**
